первый коммит
mamuangkuan/stellar-burgers pull request #1
Opened 2024-10-27 21:15 UTC by mamuangkuan

первый коммит

2024-10-27 22:00 UTC, SergeyK2004 requested changes
Здравствуйте. 

Работа проделана огромная

Что сделано отлично:
Отлично сделана логика проверки, был ли пользователь на сайте, и показывать ли страницу с деталями, а не модально окно. Весь заявленный функционал реализован. Здорово, что выделяется активная страница в главном меню. Бургер корректно собирается с возможностью менять ингредиенты местами.

Что нужно исправить:

* https://disk.yandex.ru/d/jEAgmPPSaSSsVw  Отсутствует статус заказа. Сверьтесь с макетом. Проверьте так-же отображение заказа в отдельной странице, на ней отсутствует и статус заказа и заголовок.
* https://disk.yandex.ru/d/hcvwxdRy-bLf1g Нужно центрировать контент на странице с деталями ингредиента.  Не отображается заголовок формы.
* https://disk.yandex.ru/d/ljyIA33ZCsxISw Обратите внимание, что иконки в меню должны так-же изменять свое отображение в зависимости от активности пункта меню. Сверьтесь с макетом.

Исправьте, пожалуйста, недочеты и работа будет принята. Пожалуйста, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12) перед отправкой на ревью. 
Напоминаю, что работа может быть принята только после исправления всех критических замечаний Нужно исправить.


Удачного рефакторинга кода.

2024-10-27 22:00 UTC, SergeyK2004 commented on src/components/burger-ingredient/burger-ingredient.tsx
> +      const ingredientWithId = { ...ingredient, id: nanoid() };
Отлично:
Правильно, что генерируете id за пределами редьюсера. Хорошим решением было бы так-же вынести генерацию id в блок prepare редюсера.

2024-10-28 21:15 UTC, mamuangkuan commented
Здравствуйте!

Внесены следующие изменения:

1) Исправлено отображение статуса заказа.
2) Использован NavLink для пунктов меню вместо LInk.
3) Добавлены статусы активных / неактивных иконок в пунктах меню.
4) Добавлены заголовки на странице ингредиента / заказа и их стилизация в соответствии с макетом.
5) Доработана стилизация заголовков модальных окон ингредиента / заказа в соответствии с макетом.
6) Работоспособность приложения проверена, ошибки в консоли устранены.

2024-10-29 06:24 UTC, SergeyK2004 approved these changes
Отлично. Замечаний больше нет. 
Ваша работа принята. Желаю успехов в дальнейшем обучении.
Обратите внимание, что сейчас вам нужно смержить ветку review в main и после этого, при выполнении проектной работы следующего спринта создать новую ветку review, в которой вы будете покрывать приложение тестами. Старую ветку review после слияния можно удалить, чтобы она не мешала вам создавать новую.

2024-10-29 07:16 UTC, merged