Добавлен функционал тестирования Jest и Cypress
mamuangkuan/stellar-burgers pull request #2
Opened 2024-11-11 20:41 UTC by mamuangkuan

2024-11-11 21:36 UTC, SergeyK2004 requested changes
Очень хорошая работа. 
Тесты написаны аккуратно без лишнего кода. Код приятно читать. Все тесты проходят. 

Однако есть небольшие замечания к логике тестов cypress. Посмотрите их в коде.

2024-11-11 21:36 UTC, SergeyK2004 commented on cypress/e2e/burgerConstructor.cy.ts
> +  cy.intercept('GET', '/api/ingredients', {
Отлично:

Хорошо, что используете intercept

2024-11-11 21:36 UTC, SergeyK2004 commented on cypress/e2e/burgerConstructor.cy.ts
> +  cy.clearAllCookies();
Отлично:
Хорошо, что очищаете хранилище и куки после тестов

2024-11-11 21:36 UTC, SergeyK2004 commented on cypress/e2e/burgerConstructor.cy.ts
> +      .click();
**Надо исправить:**

Перед тем, как добавлять ингредиент, нужно проверить, что его нет в конструкторе. В противном случае вы не проверяете действие, а проверяете только наличие ингредиента в конструкторе, но добавился он из-за клика в кнопку "добавить" или уже был там неизвестно.
При проверке любого действия необходимо выполнить три шага:

1. Проверить, что элемент, который должен появиться в результате действия отсутствует.
2. Выполнить действие.
3. Проверить, что элемент появился в разметке.

Необходимо учесть это во всех проверках.

2024-11-11 21:36 UTC, SergeyK2004 commented on cypress/e2e/burgerConstructor.cy.ts
> +    cy.get('@modal').should('be.not.empty');
Надо исправить:
Нужно проверить отсутствие модального окна, после открытия убедиться, что в модальном окне отображается именно тот ингредиент, в который был выполнен клик

2024-11-11 21:36 UTC, SergeyK2004 commented on cypress/e2e/burgerConstructor.cy.ts
> +      'Выберите начинку'
Отлично:
Верно, после оформления заказа нужно проверить, что конструктор очистился.

2024-11-11 21:36 UTC, SergeyK2004 commented on src/components/ui/burger-constructor/burger-constructor.tsx
> +        data-testid='order_burger'
Отлично:
Хорошо, что используете дата атрибуты для тестов

2024-11-11 21:36 UTC, SergeyK2004 commented on src/services/ingredientsSlice..test.ts
> +    const action = { type: fetchIngredients.rejected.type };
Отлично:
Хорошая проверка всех асинхронных экшенов редьюсера

2024-11-11 21:36 UTC, SergeyK2004 commented on src/services/rootReducet.test.ts
> +    expect(state).toEqual(expectedInitialState);
Отлично:
Редьюсеры проверены в соответствии с заданием.

2024-11-12 14:24 UTC, mamuangkuan commented
Внесены изменения в логику работы тестов на Cypress:

1) В тесте на добавление ингредиентов в конструктор бургера сначала проверяется, что конструктор пустой
2) В тестах модальных окон сначала проверяется, что модального окна нет страницы, а при открытии добавлена проверка на соответствие ингредиента

2024-11-12 20:44 UTC, SergeyK2004 approved these changes
Отлично.
Замечательная работа. Поздравляю со сдачей проекта.
Желаю успехов в дальнейшем освоении профессии.

2024-11-13 20:01 UTC, merged